### ISSUE TITLE
Tree conflict in the translations folder for NVDA related to this addon

### ISSUE THREAD

**Issue by Adriani90** [ABuffEr/noBeepsSpeechMode#1]
Dear Alberto,

this addons seems to encounter a tree conflict which do not allow us translators to push commits to the whole translations repository. We have tried anything to solve this issue but there seems to be a tree conflict. It might have been caused after the last updates of the addon which have been uploaded on the server. Could you please look into it?

Best regards
Adriani Botez

**Comment by ABuffEr** [comment]
Hi Adriani, 
my last commit on Bitbucket repository (original, this is a copy) for this add-on is very old, so I think something went wrong on translation system, where, again, I not worked recently. 
I don't know enough translation system to apply changes, but I see that, for all languages that have conflicts (es, fa, gl), the directory name of add-on is "NoBeepsSpeechMode", instead of "noBeepsSpeechMode" (the first character must be in lowercase, not in uppercase). 
I hope this is sufficient to resolve.

**Comment by Adriani90** [comment]
Hello,

 

thank you for your fast reply. We will try to solve it that way.

 

Best

Adriani

 

Von: Alberto Buffolino <notifications@github.com> 
Gesendet: Dienstag, 8. Mai 2018 10:09
An: ABuffEr/noBeepsSpeechMode <noBeepsSpeechMode@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [ABuffEr/noBeepsSpeechMode] Tree conflict in the translations folder for NVDA related to this addon (#1)

 

Hi Adriani,
my last commit on Bitbucket repository (original, this is a copy) for this add-on is very old, so I think something went wrong on translation system, where, again, I not worked recently.
I don't know enough translation system to apply changes, but I see that, for all languages that have conflicts (es, fa, gl), the directory name of add-on is "NoBeepsSpeechMode", instead of "noBeepsSpeechMode" (the first character must be in lowercase, not in uppercase).
I hope this is sufficient to resolve.

**Comment by ABuffEr** [comment]
According to previous observation, problem seems resolved, so issue was closed.
